spring:
    application:
        name: inventory-management-system
    
    datasource:
        url: jdbc:postgresql://localhost:5432/warehouses
        username: postgres
        password: DataTab
    

    output:
        ansi:
            enabled: always



server:
    port: 8282

